# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Learning BPM'
description: "A collection of articles, tutorials, how-to guides, useful resources and more from my experience learning and implementing ProcessMaker Workflow and BPM solutions."

# Author's info
author: "'dipo Majekodunmi"
# edit 'categories' in the front matter of every post to match this username
nickname: dipole
bio: 'A technology generalist and ProcessMaker specialist. I love to learn about new technologies and figuring out how they can solve business problems.'
location: 'Lagos, Nigeria'
url: 'https://twitter.com/dipomajekodunmi'
image: 'assets/images/dipo.jpeg'

short_url: 'twitter.com/dipomajekodunmi/'
google_analytics: UA-11807540-19
disqus: learningbpm
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /
liveurl: 'https://learningbpm.com/'

# Permalinks
permalink: /:title

# gems and other configs
gems: [html-proofer, jekyll-paginate, jekyll-sitemap]

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - zopfli
